# Generated by Django 5.0.7 on 2024-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0004_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='sno',
            new_name='postSno',
        ),
    ]
