# Generated by Django 5.0.7 on 2024-08-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0006_postcomment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='image',
        ),
    ]
