# Generated by Django 5.0.7 on 2024-08-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0007_remove_postcomment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
    ]
