# Generated by Django 5.0.7 on 2024-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ali', '0008_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, help_text='Main image', null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, help_text='Image for section 1', null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, help_text='Image for section 2', null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, help_text='Short introduction or overview', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section1_content',
            field=models.TextField(blank=True, help_text='Content for section 1', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section1_title',
            field=models.CharField(blank=True, help_text='Title for section 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section2_content',
            field=models.TextField(blank=True, help_text='Content for section 2', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='section2_title',
            field=models.CharField(blank=True, help_text='Title for section 2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='Main content of the article', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
